branches:
  only:
  - master

language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pytest testpr.py; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then pytest API_web_test.py; fi'
